name: Update
on:
  workflow_dispatch:
jobs:
  UpdateAckee:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Ackee repo
      uses: actions/checkout@v3
      with:
        repository: electerious/Ackee
        path: Update
    - name: Checkout My repo
      uses: actions/checkout@v3
      with:
        repository: Mlikiowa/BlogAckee
        path: Ackee
    - name: File commit
      run: |
          mkdir temp
          rm -rf Update/.git/*
          mv -b Update/* temp/ 
          mv -b temp/* Ackee/          		
    - name: Commit files
      run: |
        cd Ackee
        git add .
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Update Ackee"
        git push -f
